// Code generated by github.com/Khan/genqlient, DO NOT EDIT.

package main

import (
	"context"
	"encoding/json"
	"fmt"
	"time"

	"github.com/Khan/genqlient/graphql"
)

// The possible states for a check suite or run conclusion.
type CheckConclusionState string

const (
	// The check suite or run requires action.
	CheckConclusionStateActionRequired CheckConclusionState = "ACTION_REQUIRED"
	// The check suite or run has been cancelled.
	CheckConclusionStateCancelled CheckConclusionState = "CANCELLED"
	// The check suite or run has failed.
	CheckConclusionStateFailure CheckConclusionState = "FAILURE"
	// The check suite or run was neutral.
	CheckConclusionStateNeutral CheckConclusionState = "NEUTRAL"
	// The check suite or run was skipped.
	CheckConclusionStateSkipped CheckConclusionState = "SKIPPED"
	// The check suite or run was marked stale by GitHub. Only GitHub can use this conclusion.
	CheckConclusionStateStale CheckConclusionState = "STALE"
	// The check suite or run has failed at startup.
	CheckConclusionStateStartupFailure CheckConclusionState = "STARTUP_FAILURE"
	// The check suite or run has succeeded.
	CheckConclusionStateSuccess CheckConclusionState = "SUCCESS"
	// The check suite or run has timed out.
	CheckConclusionStateTimedOut CheckConclusionState = "TIMED_OUT"
)

// The possible states for a check suite or run status.
type CheckStatusState string

const (
	// The check suite or run has been completed.
	CheckStatusStateCompleted CheckStatusState = "COMPLETED"
	// The check suite or run is in progress.
	CheckStatusStateInProgress CheckStatusState = "IN_PROGRESS"
	// The check suite or run is in pending state.
	CheckStatusStatePending CheckStatusState = "PENDING"
	// The check suite or run has been queued.
	CheckStatusStateQueued CheckStatusState = "QUEUED"
	// The check suite or run has been requested.
	CheckStatusStateRequested CheckStatusState = "REQUESTED"
	// The check suite or run is in waiting state.
	CheckStatusStateWaiting CheckStatusState = "WAITING"
)

// The possible states in which a deployment can be.
type DeploymentState string

const (
	// The pending deployment was not updated after 30 minutes.
	DeploymentStateAbandoned DeploymentState = "ABANDONED"
	// The deployment is currently active.
	DeploymentStateActive DeploymentState = "ACTIVE"
	// An inactive transient deployment.
	DeploymentStateDestroyed DeploymentState = "DESTROYED"
	// The deployment experienced an error.
	DeploymentStateError DeploymentState = "ERROR"
	// The deployment has failed.
	DeploymentStateFailure DeploymentState = "FAILURE"
	// The deployment is inactive.
	DeploymentStateInactive DeploymentState = "INACTIVE"
	// The deployment is in progress.
	DeploymentStateInProgress DeploymentState = "IN_PROGRESS"
	// The deployment is pending.
	DeploymentStatePending DeploymentState = "PENDING"
	// The deployment has queued
	DeploymentStateQueued DeploymentState = "QUEUED"
	// The deployment was successful.
	DeploymentStateSuccess DeploymentState = "SUCCESS"
	// The deployment is waiting.
	DeploymentStateWaiting DeploymentState = "WAITING"
)

// The possible states for a deployment status.
type DeploymentStatusState string

const (
	// The deployment experienced an error.
	DeploymentStatusStateError DeploymentStatusState = "ERROR"
	// The deployment has failed.
	DeploymentStatusStateFailure DeploymentStatusState = "FAILURE"
	// The deployment is inactive.
	DeploymentStatusStateInactive DeploymentStatusState = "INACTIVE"
	// The deployment is in progress.
	DeploymentStatusStateInProgress DeploymentStatusState = "IN_PROGRESS"
	// The deployment is pending.
	DeploymentStatusStatePending DeploymentStatusState = "PENDING"
	// The deployment is queued
	DeploymentStatusStateQueued DeploymentStatusState = "QUEUED"
	// The deployment was successful.
	DeploymentStatusStateSuccess DeploymentStatusState = "SUCCESS"
	// The deployment is waiting.
	DeploymentStatusStateWaiting DeploymentStatusState = "WAITING"
)

// The possible commit status states.
type StatusState string

const (
	// Status is errored.
	StatusStateError StatusState = "ERROR"
	// Status is expected.
	StatusStateExpected StatusState = "EXPECTED"
	// Status is failing.
	StatusStateFailure StatusState = "FAILURE"
	// Status is pending.
	StatusStatePending StatusState = "PENDING"
	// Status is successful.
	StatusStateSuccess StatusState = "SUCCESS"
)

// __createIssueInput is used internally by genqlient
type __createIssueInput struct {
	Body         string `json:"Body"`
	Title        string `json:"Title"`
	RepositoryId string `json:"RepositoryId"`
}

// GetBody returns __createIssueInput.Body, and is useful for accessing the field via an interface.
func (v *__createIssueInput) GetBody() string { return v.Body }

// GetTitle returns __createIssueInput.Title, and is useful for accessing the field via an interface.
func (v *__createIssueInput) GetTitle() string { return v.Title }

// GetRepositoryId returns __createIssueInput.RepositoryId, and is useful for accessing the field via an interface.
func (v *__createIssueInput) GetRepositoryId() string { return v.RepositoryId }

// __createPullRequestInput is used internally by genqlient
type __createPullRequestInput struct {
	BaseRefName  string `json:"BaseRefName"`
	Body         string `json:"Body"`
	HeadRefName  string `json:"HeadRefName"`
	RepositoryId string `json:"RepositoryId"`
	Title        string `json:"Title"`
}

// GetBaseRefName returns __createPullRequestInput.BaseRefName, and is useful for accessing the field via an interface.
func (v *__createPullRequestInput) GetBaseRefName() string { return v.BaseRefName }

// GetBody returns __createPullRequestInput.Body, and is useful for accessing the field via an interface.
func (v *__createPullRequestInput) GetBody() string { return v.Body }

// GetHeadRefName returns __createPullRequestInput.HeadRefName, and is useful for accessing the field via an interface.
func (v *__createPullRequestInput) GetHeadRefName() string { return v.HeadRefName }

// GetRepositoryId returns __createPullRequestInput.RepositoryId, and is useful for accessing the field via an interface.
func (v *__createPullRequestInput) GetRepositoryId() string { return v.RepositoryId }

// GetTitle returns __createPullRequestInput.Title, and is useful for accessing the field via an interface.
func (v *__createPullRequestInput) GetTitle() string { return v.Title }

// __getCommitGitHubActionsRunsInput is used internally by genqlient
type __getCommitGitHubActionsRunsInput struct {
	Owner     string `json:"owner"`
	Repo      string `json:"repo"`
	CommitSha string `json:"commitSha"`
}

// GetOwner returns __getCommitGitHubActionsRunsInput.Owner, and is useful for accessing the field via an interface.
func (v *__getCommitGitHubActionsRunsInput) GetOwner() string { return v.Owner }

// GetRepo returns __getCommitGitHubActionsRunsInput.Repo, and is useful for accessing the field via an interface.
func (v *__getCommitGitHubActionsRunsInput) GetRepo() string { return v.Repo }

// GetCommitSha returns __getCommitGitHubActionsRunsInput.CommitSha, and is useful for accessing the field via an interface.
func (v *__getCommitGitHubActionsRunsInput) GetCommitSha() string { return v.CommitSha }

// __getLatestDeploymentsInput is used internally by genqlient
type __getLatestDeploymentsInput struct {
	Owner string `json:"owner"`
	Repo  string `json:"repo"`
}

// GetOwner returns __getLatestDeploymentsInput.Owner, and is useful for accessing the field via an interface.
func (v *__getLatestDeploymentsInput) GetOwner() string { return v.Owner }

// GetRepo returns __getLatestDeploymentsInput.Repo, and is useful for accessing the field via an interface.
func (v *__getLatestDeploymentsInput) GetRepo() string { return v.Repo }

// __getPullRequestStatusCheckRollupInput is used internally by genqlient
type __getPullRequestStatusCheckRollupInput struct {
	Owner    string `json:"owner"`
	Repo     string `json:"repo"`
	PrNumber int    `json:"prNumber"`
}

// GetOwner returns __getPullRequestStatusCheckRollupInput.Owner, and is useful for accessing the field via an interface.
func (v *__getPullRequestStatusCheckRollupInput) GetOwner() string { return v.Owner }

// GetRepo returns __getPullRequestStatusCheckRollupInput.Repo, and is useful for accessing the field via an interface.
func (v *__getPullRequestStatusCheckRollupInput) GetRepo() string { return v.Repo }

// GetPrNumber returns __getPullRequestStatusCheckRollupInput.PrNumber, and is useful for accessing the field via an interface.
func (v *__getPullRequestStatusCheckRollupInput) GetPrNumber() int { return v.PrNumber }

// __getRepoIdInput is used internally by genqlient
type __getRepoIdInput struct {
	Owner string `json:"Owner"`
	Name  string `json:"Name"`
}

// GetOwner returns __getRepoIdInput.Owner, and is useful for accessing the field via an interface.
func (v *__getRepoIdInput) GetOwner() string { return v.Owner }

// GetName returns __getRepoIdInput.Name, and is useful for accessing the field via an interface.
func (v *__getRepoIdInput) GetName() string { return v.Name }

// __getUserInput is used internally by genqlient
type __getUserInput struct {
	Login string `json:"Login"`
}

// GetLogin returns __getUserInput.Login, and is useful for accessing the field via an interface.
func (v *__getUserInput) GetLogin() string { return v.Login }

// __mergePullRequestInput is used internally by genqlient
type __mergePullRequestInput struct {
	PullRequestId string `json:"pullRequestId"`
}

// GetPullRequestId returns __mergePullRequestInput.PullRequestId, and is useful for accessing the field via an interface.
func (v *__mergePullRequestInput) GetPullRequestId() string { return v.PullRequestId }

// createIssueCreateIssueCreateIssuePayload includes the requested fields of the GraphQL type CreateIssuePayload.
// The GraphQL type's documentation follows.
//
// Autogenerated return type of CreateIssue
type createIssueCreateIssueCreateIssuePayload struct {
	// The new issue.
	Issue createIssueCreateIssueCreateIssuePayloadIssue `json:"issue"`
}

// GetIssue returns createIssueCreateIssueCreateIssuePayload.Issue, and is useful for accessing the field via an interface.
func (v *createIssueCreateIssueCreateIssuePayload) GetIssue() createIssueCreateIssueCreateIssuePayloadIssue {
	return v.Issue
}

// createIssueCreateIssueCreateIssuePayloadIssue includes the requested fields of the GraphQL type Issue.
// The GraphQL type's documentation follows.
//
// An Issue is a place to discuss ideas, enhancements, tasks, and bugs for a project.
type createIssueCreateIssueCreateIssuePayloadIssue struct {
	// The Node ID of the Issue object
	Id string `json:"id"`
}

// GetId returns createIssueCreateIssueCreateIssuePayloadIssue.Id, and is useful for accessing the field via an interface.
func (v *createIssueCreateIssueCreateIssuePayloadIssue) GetId() string { return v.Id }

// createIssueResponse is returned by createIssue on success.
type createIssueResponse struct {
	// Creates a new issue.
	CreateIssue createIssueCreateIssueCreateIssuePayload `json:"createIssue"`
}

// GetCreateIssue returns createIssueResponse.CreateIssue, and is useful for accessing the field via an interface.
func (v *createIssueResponse) GetCreateIssue() createIssueCreateIssueCreateIssuePayload {
	return v.CreateIssue
}

// createPullRequestCreatePullRequestCreatePullRequestPayload includes the requested fields of the GraphQL type CreatePullRequestPayload.
// The GraphQL type's documentation follows.
//
// Autogenerated return type of CreatePullRequest
type createPullRequestCreatePullRequestCreatePullRequestPayload struct {
	// The new pull request.
	PullRequest createPullRequestCreatePullRequestCreatePullRequestPayloadPullRequest `json:"pullRequest"`
}

// GetPullRequest returns createPullRequestCreatePullRequestCreatePullRequestPayload.PullRequest, and is useful for accessing the field via an interface.
func (v *createPullRequestCreatePullRequestCreatePullRequestPayload) GetPullRequest() createPullRequestCreatePullRequestCreatePullRequestPayloadPullRequest {
	return v.PullRequest
}

// createPullRequestCreatePullRequestCreatePullRequestPayloadPullRequest includes the requested fields of the GraphQL type PullRequest.
// The GraphQL type's documentation follows.
//
// A repository pull request.
type createPullRequestCreatePullRequestCreatePullRequestPayloadPullRequest struct {
	// The Node ID of the PullRequest object
	Id string `json:"id"`
	// Identifies the pull request number.
	Number int `json:"number"`
}

// GetId returns createPullRequestCreatePullRequestCreatePullRequestPayloadPullRequest.Id, and is useful for accessing the field via an interface.
func (v *createPullRequestCreatePullRequestCreatePullRequestPayloadPullRequest) GetId() string {
	return v.Id
}

// GetNumber returns createPullRequestCreatePullRequestCreatePullRequestPayloadPullRequest.Number, and is useful for accessing the field via an interface.
func (v *createPullRequestCreatePullRequestCreatePullRequestPayloadPullRequest) GetNumber() int {
	return v.Number
}

// createPullRequestResponse is returned by createPullRequest on success.
type createPullRequestResponse struct {
	// Create a new pull request
	CreatePullRequest createPullRequestCreatePullRequestCreatePullRequestPayload `json:"createPullRequest"`
}

// GetCreatePullRequest returns createPullRequestResponse.CreatePullRequest, and is useful for accessing the field via an interface.
func (v *createPullRequestResponse) GetCreatePullRequest() createPullRequestCreatePullRequestCreatePullRequestPayload {
	return v.CreatePullRequest
}

// getCommitGitHubActionsRunsRepository includes the requested fields of the GraphQL type Repository.
// The GraphQL type's documentation follows.
//
// A repository contains the content for a project.
type getCommitGitHubActionsRunsRepository struct {
	// A Git object in the repository
	Object getCommitGitHubActionsRunsRepositoryObjectGitObject `json:"-"`
}

// GetObject returns getCommitGitHubActionsRunsRepository.Object, and is useful for accessing the field via an interface.
func (v *getCommitGitHubActionsRunsRepository) GetObject() getCommitGitHubActionsRunsRepositoryObjectGitObject {
	return v.Object
}

func (v *getCommitGitHubActionsRunsRepository) UnmarshalJSON(b []byte) error {

	if string(b) == "null" {
		return nil
	}

	var firstPass struct {
		*getCommitGitHubActionsRunsRepository
		Object json.RawMessage `json:"object"`
		graphql.NoUnmarshalJSON
	}
	firstPass.getCommitGitHubActionsRunsRepository = v

	err := json.Unmarshal(b, &firstPass)
	if err != nil {
		return err
	}

	{
		dst := &v.Object
		src := firstPass.Object
		if len(src) != 0 && string(src) != "null" {
			err = __unmarshalgetCommitGitHubActionsRunsRepositoryObjectGitObject(
				src, dst)
			if err != nil {
				return fmt.Errorf(
					"unable to unmarshal getCommitGitHubActionsRunsRepository.Object: %w", err)
			}
		}
	}
	return nil
}

type __premarshalgetCommitGitHubActionsRunsRepository struct {
	Object json.RawMessage `json:"object"`
}

func (v *getCommitGitHubActionsRunsRepository) MarshalJSON() ([]byte, error) {
	premarshaled, err := v.__premarshalJSON()
	if err != nil {
		return nil, err
	}
	return json.Marshal(premarshaled)
}

func (v *getCommitGitHubActionsRunsRepository) __premarshalJSON() (*__premarshalgetCommitGitHubActionsRunsRepository, error) {
	var retval __premarshalgetCommitGitHubActionsRunsRepository

	{

		dst := &retval.Object
		src := v.Object
		var err error
		*dst, err = __marshalgetCommitGitHubActionsRunsRepositoryObjectGitObject(
			&src)
		if err != nil {
			return nil, fmt.Errorf(
				"unable to marshal getCommitGitHubActionsRunsRepository.Object: %w", err)
		}
	}
	return &retval, nil
}

// getCommitGitHubActionsRunsRepositoryObjectBlob includes the requested fields of the GraphQL type Blob.
// The GraphQL type's documentation follows.
//
// Represents a Git blob.
type getCommitGitHubActionsRunsRepositoryObjectBlob struct {
	Typename string `json:"__typename"`
}

// GetTypename returns getCommitGitHubActionsRunsRepositoryObjectBlob.Typename, and is useful for accessing the field via an interface.
func (v *getCommitGitHubActionsRunsRepositoryObjectBlob) GetTypename() string { return v.Typename }

// getCommitGitHubActionsRunsRepositoryObjectCommit includes the requested fields of the GraphQL type Commit.
// The GraphQL type's documentation follows.
//
// Represents a Git commit.
type getCommitGitHubActionsRunsRepositoryObjectCommit struct {
	Typename string `json:"__typename"`
	// Check and Status rollup information for this commit.
	StatusCheckRollup getCommitGitHubActionsRunsRepositoryObjectCommitStatusCheckRollup `json:"statusCheckRollup"`
}

// GetTypename returns getCommitGitHubActionsRunsRepositoryObjectCommit.Typename, and is useful for accessing the field via an interface.
func (v *getCommitGitHubActionsRunsRepositoryObjectCommit) GetTypename() string { return v.Typename }

// GetStatusCheckRollup returns getCommitGitHubActionsRunsRepositoryObjectCommit.StatusCheckRollup, and is useful for accessing the field via an interface.
func (v *getCommitGitHubActionsRunsRepositoryObjectCommit) GetStatusCheckRollup() getCommitGitHubActionsRunsRepositoryObjectCommitStatusCheckRollup {
	return v.StatusCheckRollup
}

// getCommitGitHubActionsRunsRepositoryObjectCommitStatusCheckRollup includes the requested fields of the GraphQL type StatusCheckRollup.
// The GraphQL type's documentation follows.
//
// Represents the rollup for both the check runs and status for a commit.
type getCommitGitHubActionsRunsRepositoryObjectCommitStatusCheckRollup struct {
	// A list of status contexts and check runs for this commit.
	Contexts getCommitGitHubActionsRunsRepositoryObjectCommitStatusCheckRollupContextsStatusCheckRollupContextConnection `json:"contexts"`
}

// GetContexts returns getCommitGitHubActionsRunsRepositoryObjectCommitStatusCheckRollup.Contexts, and is useful for accessing the field via an interface.
func (v *getCommitGitHubActionsRunsRepositoryObjectCommitStatusCheckRollup) GetContexts() getCommitGitHubActionsRunsRepositoryObjectCommitStatusCheckRollupContextsStatusCheckRollupContextConnection {
	return v.Contexts
}

// getCommitGitHubActionsRunsRepositoryObjectCommitStatusCheckRollupContextsStatusCheckRollupContextConnection includes the requested fields of the GraphQL type StatusCheckRollupContextConnection.
// The GraphQL type's documentation follows.
//
// The connection type for StatusCheckRollupContext.
type getCommitGitHubActionsRunsRepositoryObjectCommitStatusCheckRollupContextsStatusCheckRollupContextConnection struct {
	// A list of nodes.
	Nodes []getCommitGitHubActionsRunsRepositoryObjectCommitStatusCheckRollupContextsStatusCheckRollupContextConnectionNodesStatusCheckRollupContext `json:"-"`
}

// GetNodes returns getCommitGitHubActionsRunsRepositoryObjectCommitStatusCheckRollupContextsStatusCheckRollupContextConnection.Nodes, and is useful for accessing the field via an interface.
func (v *getCommitGitHubActionsRunsRepositoryObjectCommitStatusCheckRollupContextsStatusCheckRollupContextConnection) GetNodes() []getCommitGitHubActionsRunsRepositoryObjectCommitStatusCheckRollupContextsStatusCheckRollupContextConnectionNodesStatusCheckRollupContext {
	return v.Nodes
}

func (v *getCommitGitHubActionsRunsRepositoryObjectCommitStatusCheckRollupContextsStatusCheckRollupContextConnection) UnmarshalJSON(b []byte) error {

	if string(b) == "null" {
		return nil
	}

	var firstPass struct {
		*getCommitGitHubActionsRunsRepositoryObjectCommitStatusCheckRollupContextsStatusCheckRollupContextConnection
		Nodes []json.RawMessage `json:"nodes"`
		graphql.NoUnmarshalJSON
	}
	firstPass.getCommitGitHubActionsRunsRepositoryObjectCommitStatusCheckRollupContextsStatusCheckRollupContextConnection = v

	err := json.Unmarshal(b, &firstPass)
	if err != nil {
		return err
	}

	{
		dst := &v.Nodes
		src := firstPass.Nodes
		*dst = make(
			[]getCommitGitHubActionsRunsRepositoryObjectCommitStatusCheckRollupContextsStatusCheckRollupContextConnectionNodesStatusCheckRollupContext,
			len(src))
		for i, src := range src {
			dst := &(*dst)[i]
			if len(src) != 0 && string(src) != "null" {
				err = __unmarshalgetCommitGitHubActionsRunsRepositoryObjectCommitStatusCheckRollupContextsStatusCheckRollupContextConnectionNodesStatusCheckRollupContext(
					src, dst)
				if err != nil {
					return fmt.Errorf(
						"unable to unmarshal getCommitGitHubActionsRunsRepositoryObjectCommitStatusCheckRollupContextsStatusCheckRollupContextConnection.Nodes: %w", err)
				}
			}
		}
	}
	return nil
}

type __premarshalgetCommitGitHubActionsRunsRepositoryObjectCommitStatusCheckRollupContextsStatusCheckRollupContextConnection struct {
	Nodes []json.RawMessage `json:"nodes"`
}

func (v *getCommitGitHubActionsRunsRepositoryObjectCommitStatusCheckRollupContextsStatusCheckRollupContextConnection) MarshalJSON() ([]byte, error) {
	premarshaled, err := v.__premarshalJSON()
	if err != nil {
		return nil, err
	}
	return json.Marshal(premarshaled)
}

func (v *getCommitGitHubActionsRunsRepositoryObjectCommitStatusCheckRollupContextsStatusCheckRollupContextConnection) __premarshalJSON() (*__premarshalgetCommitGitHubActionsRunsRepositoryObjectCommitStatusCheckRollupContextsStatusCheckRollupContextConnection, error) {
	var retval __premarshalgetCommitGitHubActionsRunsRepositoryObjectCommitStatusCheckRollupContextsStatusCheckRollupContextConnection

	{

		dst := &retval.Nodes
		src := v.Nodes
		*dst = make(
			[]json.RawMessage,
			len(src))
		for i, src := range src {
			dst := &(*dst)[i]
			var err error
			*dst, err = __marshalgetCommitGitHubActionsRunsRepositoryObjectCommitStatusCheckRollupContextsStatusCheckRollupContextConnectionNodesStatusCheckRollupContext(
				&src)
			if err != nil {
				return nil, fmt.Errorf(
					"unable to marshal getCommitGitHubActionsRunsRepositoryObjectCommitStatusCheckRollupContextsStatusCheckRollupContextConnection.Nodes: %w", err)
			}
		}
	}
	return &retval, nil
}

// getCommitGitHubActionsRunsRepositoryObjectCommitStatusCheckRollupContextsStatusCheckRollupContextConnectionNodesCheckRun includes the requested fields of the GraphQL type CheckRun.
// The GraphQL type's documentation follows.
//
// A check run.
type getCommitGitHubActionsRunsRepositoryObjectCommitStatusCheckRollupContextsStatusCheckRollupContextConnectionNodesCheckRun struct {
	Typename string `json:"__typename"`
	// The name of the check for this check run.
	Name string `json:"name"`
	// The conclusion of the check run.
	Conclusion CheckConclusionState `json:"conclusion"`
	// The current status of the check run.
	Status CheckStatusState `json:"status"`
	// The URL from which to find full details of the check run on the integrator's site.
	DetailsUrl string `json:"detailsUrl"`
}

// GetTypename returns getCommitGitHubActionsRunsRepositoryObjectCommitStatusCheckRollupContextsStatusCheckRollupContextConnectionNodesCheckRun.Typename, and is useful for accessing the field via an interface.
func (v *getCommitGitHubActionsRunsRepositoryObjectCommitStatusCheckRollupContextsStatusCheckRollupContextConnectionNodesCheckRun) GetTypename() string {
	return v.Typename
}

// GetName returns getCommitGitHubActionsRunsRepositoryObjectCommitStatusCheckRollupContextsStatusCheckRollupContextConnectionNodesCheckRun.Name, and is useful for accessing the field via an interface.
func (v *getCommitGitHubActionsRunsRepositoryObjectCommitStatusCheckRollupContextsStatusCheckRollupContextConnectionNodesCheckRun) GetName() string {
	return v.Name
}

// GetConclusion returns getCommitGitHubActionsRunsRepositoryObjectCommitStatusCheckRollupContextsStatusCheckRollupContextConnectionNodesCheckRun.Conclusion, and is useful for accessing the field via an interface.
func (v *getCommitGitHubActionsRunsRepositoryObjectCommitStatusCheckRollupContextsStatusCheckRollupContextConnectionNodesCheckRun) GetConclusion() CheckConclusionState {
	return v.Conclusion
}

// GetStatus returns getCommitGitHubActionsRunsRepositoryObjectCommitStatusCheckRollupContextsStatusCheckRollupContextConnectionNodesCheckRun.Status, and is useful for accessing the field via an interface.
func (v *getCommitGitHubActionsRunsRepositoryObjectCommitStatusCheckRollupContextsStatusCheckRollupContextConnectionNodesCheckRun) GetStatus() CheckStatusState {
	return v.Status
}

// GetDetailsUrl returns getCommitGitHubActionsRunsRepositoryObjectCommitStatusCheckRollupContextsStatusCheckRollupContextConnectionNodesCheckRun.DetailsUrl, and is useful for accessing the field via an interface.
func (v *getCommitGitHubActionsRunsRepositoryObjectCommitStatusCheckRollupContextsStatusCheckRollupContextConnectionNodesCheckRun) GetDetailsUrl() string {
	return v.DetailsUrl
}

// getCommitGitHubActionsRunsRepositoryObjectCommitStatusCheckRollupContextsStatusCheckRollupContextConnectionNodesStatusCheckRollupContext includes the requested fields of the GraphQL interface StatusCheckRollupContext.
//
// getCommitGitHubActionsRunsRepositoryObjectCommitStatusCheckRollupContextsStatusCheckRollupContextConnectionNodesStatusCheckRollupContext is implemented by the following types:
// getCommitGitHubActionsRunsRepositoryObjectCommitStatusCheckRollupContextsStatusCheckRollupContextConnectionNodesCheckRun
// getCommitGitHubActionsRunsRepositoryObjectCommitStatusCheckRollupContextsStatusCheckRollupContextConnectionNodesStatusContext
// The GraphQL type's documentation follows.
//
// Types that can be inside a StatusCheckRollup context.
type getCommitGitHubActionsRunsRepositoryObjectCommitStatusCheckRollupContextsStatusCheckRollupContextConnectionNodesStatusCheckRollupContext interface {
	implementsGraphQLInterfacegetCommitGitHubActionsRunsRepositoryObjectCommitStatusCheckRollupContextsStatusCheckRollupContextConnectionNodesStatusCheckRollupContext()
	// GetTypename returns the receiver's concrete GraphQL type-name (see interface doc for possible values).
	GetTypename() string
}

func (v *getCommitGitHubActionsRunsRepositoryObjectCommitStatusCheckRollupContextsStatusCheckRollupContextConnectionNodesCheckRun) implementsGraphQLInterfacegetCommitGitHubActionsRunsRepositoryObjectCommitStatusCheckRollupContextsStatusCheckRollupContextConnectionNodesStatusCheckRollupContext() {
}
func (v *getCommitGitHubActionsRunsRepositoryObjectCommitStatusCheckRollupContextsStatusCheckRollupContextConnectionNodesStatusContext) implementsGraphQLInterfacegetCommitGitHubActionsRunsRepositoryObjectCommitStatusCheckRollupContextsStatusCheckRollupContextConnectionNodesStatusCheckRollupContext() {
}

func __unmarshalgetCommitGitHubActionsRunsRepositoryObjectCommitStatusCheckRollupContextsStatusCheckRollupContextConnectionNodesStatusCheckRollupContext(b []byte, v *getCommitGitHubActionsRunsRepositoryObjectCommitStatusCheckRollupContextsStatusCheckRollupContextConnectionNodesStatusCheckRollupContext) error {
	if string(b) == "null" {
		return nil
	}

	var tn struct {
		TypeName string `json:"__typename"`
	}
	err := json.Unmarshal(b, &tn)
	if err != nil {
		return err
	}

	switch tn.TypeName {
	case "CheckRun":
		*v = new(getCommitGitHubActionsRunsRepositoryObjectCommitStatusCheckRollupContextsStatusCheckRollupContextConnectionNodesCheckRun)
		return json.Unmarshal(b, *v)
	case "StatusContext":
		*v = new(getCommitGitHubActionsRunsRepositoryObjectCommitStatusCheckRollupContextsStatusCheckRollupContextConnectionNodesStatusContext)
		return json.Unmarshal(b, *v)
	case "":
		return fmt.Errorf(
			"response was missing StatusCheckRollupContext.__typename")
	default:
		return fmt.Errorf(
			`unexpected concrete type for getCommitGitHubActionsRunsRepositoryObjectCommitStatusCheckRollupContextsStatusCheckRollupContextConnectionNodesStatusCheckRollupContext: "%v"`, tn.TypeName)
	}
}

func __marshalgetCommitGitHubActionsRunsRepositoryObjectCommitStatusCheckRollupContextsStatusCheckRollupContextConnectionNodesStatusCheckRollupContext(v *getCommitGitHubActionsRunsRepositoryObjectCommitStatusCheckRollupContextsStatusCheckRollupContextConnectionNodesStatusCheckRollupContext) ([]byte, error) {

	var typename string
	switch v := (*v).(type) {
	case *getCommitGitHubActionsRunsRepositoryObjectCommitStatusCheckRollupContextsStatusCheckRollupContextConnectionNodesCheckRun:
		typename = "CheckRun"

		result := struct {
			TypeName string `json:"__typename"`
			*getCommitGitHubActionsRunsRepositoryObjectCommitStatusCheckRollupContextsStatusCheckRollupContextConnectionNodesCheckRun
		}{typename, v}
		return json.Marshal(result)
	case *getCommitGitHubActionsRunsRepositoryObjectCommitStatusCheckRollupContextsStatusCheckRollupContextConnectionNodesStatusContext:
		typename = "StatusContext"

		result := struct {
			TypeName string `json:"__typename"`
			*getCommitGitHubActionsRunsRepositoryObjectCommitStatusCheckRollupContextsStatusCheckRollupContextConnectionNodesStatusContext
		}{typename, v}
		return json.Marshal(result)
	case nil:
		return []byte("null"), nil
	default:
		return nil, fmt.Errorf(
			`unexpected concrete type for getCommitGitHubActionsRunsRepositoryObjectCommitStatusCheckRollupContextsStatusCheckRollupContextConnectionNodesStatusCheckRollupContext: "%T"`, v)
	}
}

// getCommitGitHubActionsRunsRepositoryObjectCommitStatusCheckRollupContextsStatusCheckRollupContextConnectionNodesStatusContext includes the requested fields of the GraphQL type StatusContext.
// The GraphQL type's documentation follows.
//
// Represents an individual commit status context
type getCommitGitHubActionsRunsRepositoryObjectCommitStatusCheckRollupContextsStatusCheckRollupContextConnectionNodesStatusContext struct {
	Typename string `json:"__typename"`
}

// GetTypename returns getCommitGitHubActionsRunsRepositoryObjectCommitStatusCheckRollupContextsStatusCheckRollupContextConnectionNodesStatusContext.Typename, and is useful for accessing the field via an interface.
func (v *getCommitGitHubActionsRunsRepositoryObjectCommitStatusCheckRollupContextsStatusCheckRollupContextConnectionNodesStatusContext) GetTypename() string {
	return v.Typename
}

// getCommitGitHubActionsRunsRepositoryObjectGitObject includes the requested fields of the GraphQL interface GitObject.
//
// getCommitGitHubActionsRunsRepositoryObjectGitObject is implemented by the following types:
// getCommitGitHubActionsRunsRepositoryObjectBlob
// getCommitGitHubActionsRunsRepositoryObjectCommit
// getCommitGitHubActionsRunsRepositoryObjectTag
// getCommitGitHubActionsRunsRepositoryObjectTree
// The GraphQL type's documentation follows.
//
// Represents a Git object.
type getCommitGitHubActionsRunsRepositoryObjectGitObject interface {
	implementsGraphQLInterfacegetCommitGitHubActionsRunsRepositoryObjectGitObject()
	// GetTypename returns the receiver's concrete GraphQL type-name (see interface doc for possible values).
	GetTypename() string
}

func (v *getCommitGitHubActionsRunsRepositoryObjectBlob) implementsGraphQLInterfacegetCommitGitHubActionsRunsRepositoryObjectGitObject() {
}
func (v *getCommitGitHubActionsRunsRepositoryObjectCommit) implementsGraphQLInterfacegetCommitGitHubActionsRunsRepositoryObjectGitObject() {
}
func (v *getCommitGitHubActionsRunsRepositoryObjectTag) implementsGraphQLInterfacegetCommitGitHubActionsRunsRepositoryObjectGitObject() {
}
func (v *getCommitGitHubActionsRunsRepositoryObjectTree) implementsGraphQLInterfacegetCommitGitHubActionsRunsRepositoryObjectGitObject() {
}

func __unmarshalgetCommitGitHubActionsRunsRepositoryObjectGitObject(b []byte, v *getCommitGitHubActionsRunsRepositoryObjectGitObject) error {
	if string(b) == "null" {
		return nil
	}

	var tn struct {
		TypeName string `json:"__typename"`
	}
	err := json.Unmarshal(b, &tn)
	if err != nil {
		return err
	}

	switch tn.TypeName {
	case "Blob":
		*v = new(getCommitGitHubActionsRunsRepositoryObjectBlob)
		return json.Unmarshal(b, *v)
	case "Commit":
		*v = new(getCommitGitHubActionsRunsRepositoryObjectCommit)
		return json.Unmarshal(b, *v)
	case "Tag":
		*v = new(getCommitGitHubActionsRunsRepositoryObjectTag)
		return json.Unmarshal(b, *v)
	case "Tree":
		*v = new(getCommitGitHubActionsRunsRepositoryObjectTree)
		return json.Unmarshal(b, *v)
	case "":
		return fmt.Errorf(
			"response was missing GitObject.__typename")
	default:
		return fmt.Errorf(
			`unexpected concrete type for getCommitGitHubActionsRunsRepositoryObjectGitObject: "%v"`, tn.TypeName)
	}
}

func __marshalgetCommitGitHubActionsRunsRepositoryObjectGitObject(v *getCommitGitHubActionsRunsRepositoryObjectGitObject) ([]byte, error) {

	var typename string
	switch v := (*v).(type) {
	case *getCommitGitHubActionsRunsRepositoryObjectBlob:
		typename = "Blob"

		result := struct {
			TypeName string `json:"__typename"`
			*getCommitGitHubActionsRunsRepositoryObjectBlob
		}{typename, v}
		return json.Marshal(result)
	case *getCommitGitHubActionsRunsRepositoryObjectCommit:
		typename = "Commit"

		result := struct {
			TypeName string `json:"__typename"`
			*getCommitGitHubActionsRunsRepositoryObjectCommit
		}{typename, v}
		return json.Marshal(result)
	case *getCommitGitHubActionsRunsRepositoryObjectTag:
		typename = "Tag"

		result := struct {
			TypeName string `json:"__typename"`
			*getCommitGitHubActionsRunsRepositoryObjectTag
		}{typename, v}
		return json.Marshal(result)
	case *getCommitGitHubActionsRunsRepositoryObjectTree:
		typename = "Tree"

		result := struct {
			TypeName string `json:"__typename"`
			*getCommitGitHubActionsRunsRepositoryObjectTree
		}{typename, v}
		return json.Marshal(result)
	case nil:
		return []byte("null"), nil
	default:
		return nil, fmt.Errorf(
			`unexpected concrete type for getCommitGitHubActionsRunsRepositoryObjectGitObject: "%T"`, v)
	}
}

// getCommitGitHubActionsRunsRepositoryObjectTag includes the requested fields of the GraphQL type Tag.
// The GraphQL type's documentation follows.
//
// Represents a Git tag.
type getCommitGitHubActionsRunsRepositoryObjectTag struct {
	Typename string `json:"__typename"`
}

// GetTypename returns getCommitGitHubActionsRunsRepositoryObjectTag.Typename, and is useful for accessing the field via an interface.
func (v *getCommitGitHubActionsRunsRepositoryObjectTag) GetTypename() string { return v.Typename }

// getCommitGitHubActionsRunsRepositoryObjectTree includes the requested fields of the GraphQL type Tree.
// The GraphQL type's documentation follows.
//
// Represents a Git tree.
type getCommitGitHubActionsRunsRepositoryObjectTree struct {
	Typename string `json:"__typename"`
}

// GetTypename returns getCommitGitHubActionsRunsRepositoryObjectTree.Typename, and is useful for accessing the field via an interface.
func (v *getCommitGitHubActionsRunsRepositoryObjectTree) GetTypename() string { return v.Typename }

// getCommitGitHubActionsRunsResponse is returned by getCommitGitHubActionsRuns on success.
type getCommitGitHubActionsRunsResponse struct {
	// Lookup a given repository by the owner and repository name.
	Repository getCommitGitHubActionsRunsRepository `json:"repository"`
}

// GetRepository returns getCommitGitHubActionsRunsResponse.Repository, and is useful for accessing the field via an interface.
func (v *getCommitGitHubActionsRunsResponse) GetRepository() getCommitGitHubActionsRunsRepository {
	return v.Repository
}

// getLatestDeploymentsRepository includes the requested fields of the GraphQL type Repository.
// The GraphQL type's documentation follows.
//
// A repository contains the content for a project.
type getLatestDeploymentsRepository struct {
	// Deployments associated with the repository
	Deployments getLatestDeploymentsRepositoryDeploymentsDeploymentConnection `json:"deployments"`
}

// GetDeployments returns getLatestDeploymentsRepository.Deployments, and is useful for accessing the field via an interface.
func (v *getLatestDeploymentsRepository) GetDeployments() getLatestDeploymentsRepositoryDeploymentsDeploymentConnection {
	return v.Deployments
}

// getLatestDeploymentsRepositoryDeploymentsDeploymentConnection includes the requested fields of the GraphQL type DeploymentConnection.
// The GraphQL type's documentation follows.
//
// The connection type for Deployment.
type getLatestDeploymentsRepositoryDeploymentsDeploymentConnection struct {
	// A list of nodes.
	Nodes []getLatestDeploymentsRepositoryDeploymentsDeploymentConnectionNodesDeployment `json:"nodes"`
}

// GetNodes returns getLatestDeploymentsRepositoryDeploymentsDeploymentConnection.Nodes, and is useful for accessing the field via an interface.
func (v *getLatestDeploymentsRepositoryDeploymentsDeploymentConnection) GetNodes() []getLatestDeploymentsRepositoryDeploymentsDeploymentConnectionNodesDeployment {
	return v.Nodes
}

// getLatestDeploymentsRepositoryDeploymentsDeploymentConnectionNodesDeployment includes the requested fields of the GraphQL type Deployment.
// The GraphQL type's documentation follows.
//
// Represents triggered deployment instance.
type getLatestDeploymentsRepositoryDeploymentsDeploymentConnectionNodesDeployment struct {
	// Identifies the date and time when the object was created.
	CreatedAt time.Time `json:"createdAt"`
	// Identifies the commit sha of the deployment.
	Commit getLatestDeploymentsRepositoryDeploymentsDeploymentConnectionNodesDeploymentCommit `json:"commit"`
	// The deployment description.
	Description string `json:"description"`
	// The current state of the deployment.
	State DeploymentState `json:"state"`
	// A list of statuses associated with the deployment.
	Statuses getLatestDeploymentsRepositoryDeploymentsDeploymentConnectionNodesDeploymentStatusesDeploymentStatusConnection `json:"statuses"`
}

// GetCreatedAt returns getLatestDeploymentsRepositoryDeploymentsDeploymentConnectionNodesDeployment.CreatedAt, and is useful for accessing the field via an interface.
func (v *getLatestDeploymentsRepositoryDeploymentsDeploymentConnectionNodesDeployment) GetCreatedAt() time.Time {
	return v.CreatedAt
}

// GetCommit returns getLatestDeploymentsRepositoryDeploymentsDeploymentConnectionNodesDeployment.Commit, and is useful for accessing the field via an interface.
func (v *getLatestDeploymentsRepositoryDeploymentsDeploymentConnectionNodesDeployment) GetCommit() getLatestDeploymentsRepositoryDeploymentsDeploymentConnectionNodesDeploymentCommit {
	return v.Commit
}

// GetDescription returns getLatestDeploymentsRepositoryDeploymentsDeploymentConnectionNodesDeployment.Description, and is useful for accessing the field via an interface.
func (v *getLatestDeploymentsRepositoryDeploymentsDeploymentConnectionNodesDeployment) GetDescription() string {
	return v.Description
}

// GetState returns getLatestDeploymentsRepositoryDeploymentsDeploymentConnectionNodesDeployment.State, and is useful for accessing the field via an interface.
func (v *getLatestDeploymentsRepositoryDeploymentsDeploymentConnectionNodesDeployment) GetState() DeploymentState {
	return v.State
}

// GetStatuses returns getLatestDeploymentsRepositoryDeploymentsDeploymentConnectionNodesDeployment.Statuses, and is useful for accessing the field via an interface.
func (v *getLatestDeploymentsRepositoryDeploymentsDeploymentConnectionNodesDeployment) GetStatuses() getLatestDeploymentsRepositoryDeploymentsDeploymentConnectionNodesDeploymentStatusesDeploymentStatusConnection {
	return v.Statuses
}

// getLatestDeploymentsRepositoryDeploymentsDeploymentConnectionNodesDeploymentCommit includes the requested fields of the GraphQL type Commit.
// The GraphQL type's documentation follows.
//
// Represents a Git commit.
type getLatestDeploymentsRepositoryDeploymentsDeploymentConnectionNodesDeploymentCommit struct {
	// The Git commit message
	Message string `json:"message"`
}

// GetMessage returns getLatestDeploymentsRepositoryDeploymentsDeploymentConnectionNodesDeploymentCommit.Message, and is useful for accessing the field via an interface.
func (v *getLatestDeploymentsRepositoryDeploymentsDeploymentConnectionNodesDeploymentCommit) GetMessage() string {
	return v.Message
}

// getLatestDeploymentsRepositoryDeploymentsDeploymentConnectionNodesDeploymentStatusesDeploymentStatusConnection includes the requested fields of the GraphQL type DeploymentStatusConnection.
// The GraphQL type's documentation follows.
//
// The connection type for DeploymentStatus.
type getLatestDeploymentsRepositoryDeploymentsDeploymentConnectionNodesDeploymentStatusesDeploymentStatusConnection struct {
	// A list of nodes.
	Nodes []getLatestDeploymentsRepositoryDeploymentsDeploymentConnectionNodesDeploymentStatusesDeploymentStatusConnectionNodesDeploymentStatus `json:"nodes"`
}

// GetNodes returns getLatestDeploymentsRepositoryDeploymentsDeploymentConnectionNodesDeploymentStatusesDeploymentStatusConnection.Nodes, and is useful for accessing the field via an interface.
func (v *getLatestDeploymentsRepositoryDeploymentsDeploymentConnectionNodesDeploymentStatusesDeploymentStatusConnection) GetNodes() []getLatestDeploymentsRepositoryDeploymentsDeploymentConnectionNodesDeploymentStatusesDeploymentStatusConnectionNodesDeploymentStatus {
	return v.Nodes
}

// getLatestDeploymentsRepositoryDeploymentsDeploymentConnectionNodesDeploymentStatusesDeploymentStatusConnectionNodesDeploymentStatus includes the requested fields of the GraphQL type DeploymentStatus.
// The GraphQL type's documentation follows.
//
// Describes the status of a given deployment attempt.
type getLatestDeploymentsRepositoryDeploymentsDeploymentConnectionNodesDeploymentStatusesDeploymentStatusConnectionNodesDeploymentStatus struct {
	// Identifies the date and time when the object was last updated.
	UpdatedAt time.Time `json:"updatedAt"`
	// Identifies the current state of the deployment.
	State DeploymentStatusState `json:"state"`
	// Identifies the environment of the deployment at the time of this deployment status
	Environment string `json:"environment"`
}

// GetUpdatedAt returns getLatestDeploymentsRepositoryDeploymentsDeploymentConnectionNodesDeploymentStatusesDeploymentStatusConnectionNodesDeploymentStatus.UpdatedAt, and is useful for accessing the field via an interface.
func (v *getLatestDeploymentsRepositoryDeploymentsDeploymentConnectionNodesDeploymentStatusesDeploymentStatusConnectionNodesDeploymentStatus) GetUpdatedAt() time.Time {
	return v.UpdatedAt
}

// GetState returns getLatestDeploymentsRepositoryDeploymentsDeploymentConnectionNodesDeploymentStatusesDeploymentStatusConnectionNodesDeploymentStatus.State, and is useful for accessing the field via an interface.
func (v *getLatestDeploymentsRepositoryDeploymentsDeploymentConnectionNodesDeploymentStatusesDeploymentStatusConnectionNodesDeploymentStatus) GetState() DeploymentStatusState {
	return v.State
}

// GetEnvironment returns getLatestDeploymentsRepositoryDeploymentsDeploymentConnectionNodesDeploymentStatusesDeploymentStatusConnectionNodesDeploymentStatus.Environment, and is useful for accessing the field via an interface.
func (v *getLatestDeploymentsRepositoryDeploymentsDeploymentConnectionNodesDeploymentStatusesDeploymentStatusConnectionNodesDeploymentStatus) GetEnvironment() string {
	return v.Environment
}

// getLatestDeploymentsResponse is returned by getLatestDeployments on success.
type getLatestDeploymentsResponse struct {
	// Lookup a given repository by the owner and repository name.
	Repository getLatestDeploymentsRepository `json:"repository"`
}

// GetRepository returns getLatestDeploymentsResponse.Repository, and is useful for accessing the field via an interface.
func (v *getLatestDeploymentsResponse) GetRepository() getLatestDeploymentsRepository {
	return v.Repository
}

// getPullRequestStatusCheckRollupRepository includes the requested fields of the GraphQL type Repository.
// The GraphQL type's documentation follows.
//
// A repository contains the content for a project.
type getPullRequestStatusCheckRollupRepository struct {
	// Returns a single pull request from the current repository by number.
	PullRequest getPullRequestStatusCheckRollupRepositoryPullRequest `json:"pullRequest"`
}

// GetPullRequest returns getPullRequestStatusCheckRollupRepository.PullRequest, and is useful for accessing the field via an interface.
func (v *getPullRequestStatusCheckRollupRepository) GetPullRequest() getPullRequestStatusCheckRollupRepositoryPullRequest {
	return v.PullRequest
}

// getPullRequestStatusCheckRollupRepositoryPullRequest includes the requested fields of the GraphQL type PullRequest.
// The GraphQL type's documentation follows.
//
// A repository pull request.
type getPullRequestStatusCheckRollupRepositoryPullRequest struct {
	// Check and Status rollup information for the PR's head ref.
	StatusCheckRollup getPullRequestStatusCheckRollupRepositoryPullRequestStatusCheckRollup `json:"statusCheckRollup"`
}

// GetStatusCheckRollup returns getPullRequestStatusCheckRollupRepositoryPullRequest.StatusCheckRollup, and is useful for accessing the field via an interface.
func (v *getPullRequestStatusCheckRollupRepositoryPullRequest) GetStatusCheckRollup() getPullRequestStatusCheckRollupRepositoryPullRequestStatusCheckRollup {
	return v.StatusCheckRollup
}

// getPullRequestStatusCheckRollupRepositoryPullRequestStatusCheckRollup includes the requested fields of the GraphQL type StatusCheckRollup.
// The GraphQL type's documentation follows.
//
// Represents the rollup for both the check runs and status for a commit.
type getPullRequestStatusCheckRollupRepositoryPullRequestStatusCheckRollup struct {
	// The combined status for the commit.
	State StatusState `json:"state"`
}

// GetState returns getPullRequestStatusCheckRollupRepositoryPullRequestStatusCheckRollup.State, and is useful for accessing the field via an interface.
func (v *getPullRequestStatusCheckRollupRepositoryPullRequestStatusCheckRollup) GetState() StatusState {
	return v.State
}

// getPullRequestStatusCheckRollupResponse is returned by getPullRequestStatusCheckRollup on success.
type getPullRequestStatusCheckRollupResponse struct {
	// Lookup a given repository by the owner and repository name.
	Repository getPullRequestStatusCheckRollupRepository `json:"repository"`
}

// GetRepository returns getPullRequestStatusCheckRollupResponse.Repository, and is useful for accessing the field via an interface.
func (v *getPullRequestStatusCheckRollupResponse) GetRepository() getPullRequestStatusCheckRollupRepository {
	return v.Repository
}

// getRepoIdRepository includes the requested fields of the GraphQL type Repository.
// The GraphQL type's documentation follows.
//
// A repository contains the content for a project.
type getRepoIdRepository struct {
	// The Node ID of the Repository object
	Id string `json:"id"`
}

// GetId returns getRepoIdRepository.Id, and is useful for accessing the field via an interface.
func (v *getRepoIdRepository) GetId() string { return v.Id }

// getRepoIdResponse is returned by getRepoId on success.
type getRepoIdResponse struct {
	// Lookup a given repository by the owner and repository name.
	Repository getRepoIdRepository `json:"repository"`
}

// GetRepository returns getRepoIdResponse.Repository, and is useful for accessing the field via an interface.
func (v *getRepoIdResponse) GetRepository() getRepoIdRepository { return v.Repository }

// getUserResponse is returned by getUser on success.
type getUserResponse struct {
	// Lookup a user by login.
	User getUserUser `json:"user"`
}

// GetUser returns getUserResponse.User, and is useful for accessing the field via an interface.
func (v *getUserResponse) GetUser() getUserUser { return v.User }

// getUserUser includes the requested fields of the GraphQL type User.
// The GraphQL type's documentation follows.
//
// A user is an individual's account on GitHub that owns repositories and can make new content.
type getUserUser struct {
	// The user's public profile name.
	TheirName string `json:"theirName"`
	// Identifies the date and time when the object was created.
	CreatedAt time.Time `json:"createdAt"`
}

// GetTheirName returns getUserUser.TheirName, and is useful for accessing the field via an interface.
func (v *getUserUser) GetTheirName() string { return v.TheirName }

// GetCreatedAt returns getUserUser.CreatedAt, and is useful for accessing the field via an interface.
func (v *getUserUser) GetCreatedAt() time.Time { return v.CreatedAt }

// getViewerResponse is returned by getViewer on success.
type getViewerResponse struct {
	// The currently authenticated user.
	Viewer getViewerViewerUser `json:"viewer"`
}

// GetViewer returns getViewerResponse.Viewer, and is useful for accessing the field via an interface.
func (v *getViewerResponse) GetViewer() getViewerViewerUser { return v.Viewer }

// getViewerViewerUser includes the requested fields of the GraphQL type User.
// The GraphQL type's documentation follows.
//
// A user is an individual's account on GitHub that owns repositories and can make new content.
type getViewerViewerUser struct {
	// The user's public profile name.
	MyName string `json:"MyName"`
	// Identifies the date and time when the object was created.
	CreatedAt time.Time `json:"createdAt"`
}

// GetMyName returns getViewerViewerUser.MyName, and is useful for accessing the field via an interface.
func (v *getViewerViewerUser) GetMyName() string { return v.MyName }

// GetCreatedAt returns getViewerViewerUser.CreatedAt, and is useful for accessing the field via an interface.
func (v *getViewerViewerUser) GetCreatedAt() time.Time { return v.CreatedAt }

// mergePullRequestMergePullRequestMergePullRequestPayload includes the requested fields of the GraphQL type MergePullRequestPayload.
// The GraphQL type's documentation follows.
//
// Autogenerated return type of MergePullRequest
type mergePullRequestMergePullRequestMergePullRequestPayload struct {
	// The pull request that was merged.
	PullRequest mergePullRequestMergePullRequestMergePullRequestPayloadPullRequest `json:"pullRequest"`
}

// GetPullRequest returns mergePullRequestMergePullRequestMergePullRequestPayload.PullRequest, and is useful for accessing the field via an interface.
func (v *mergePullRequestMergePullRequestMergePullRequestPayload) GetPullRequest() mergePullRequestMergePullRequestMergePullRequestPayloadPullRequest {
	return v.PullRequest
}

// mergePullRequestMergePullRequestMergePullRequestPayloadPullRequest includes the requested fields of the GraphQL type PullRequest.
// The GraphQL type's documentation follows.
//
// A repository pull request.
type mergePullRequestMergePullRequestMergePullRequestPayloadPullRequest struct {
	// Whether or not the pull request was merged.
	Merged bool `json:"merged"`
	// The date and time that the pull request was merged.
	MergedAt time.Time `json:"mergedAt"`
	// The commit that was created when this pull request was merged.
	MergeCommit mergePullRequestMergePullRequestMergePullRequestPayloadPullRequestMergeCommit `json:"mergeCommit"`
}

// GetMerged returns mergePullRequestMergePullRequestMergePullRequestPayloadPullRequest.Merged, and is useful for accessing the field via an interface.
func (v *mergePullRequestMergePullRequestMergePullRequestPayloadPullRequest) GetMerged() bool {
	return v.Merged
}

// GetMergedAt returns mergePullRequestMergePullRequestMergePullRequestPayloadPullRequest.MergedAt, and is useful for accessing the field via an interface.
func (v *mergePullRequestMergePullRequestMergePullRequestPayloadPullRequest) GetMergedAt() time.Time {
	return v.MergedAt
}

// GetMergeCommit returns mergePullRequestMergePullRequestMergePullRequestPayloadPullRequest.MergeCommit, and is useful for accessing the field via an interface.
func (v *mergePullRequestMergePullRequestMergePullRequestPayloadPullRequest) GetMergeCommit() mergePullRequestMergePullRequestMergePullRequestPayloadPullRequestMergeCommit {
	return v.MergeCommit
}

// mergePullRequestMergePullRequestMergePullRequestPayloadPullRequestMergeCommit includes the requested fields of the GraphQL type Commit.
// The GraphQL type's documentation follows.
//
// Represents a Git commit.
type mergePullRequestMergePullRequestMergePullRequestPayloadPullRequestMergeCommit struct {
	// The Git object ID
	Oid string `json:"oid"`
}

// GetOid returns mergePullRequestMergePullRequestMergePullRequestPayloadPullRequestMergeCommit.Oid, and is useful for accessing the field via an interface.
func (v *mergePullRequestMergePullRequestMergePullRequestPayloadPullRequestMergeCommit) GetOid() string {
	return v.Oid
}

// mergePullRequestResponse is returned by mergePullRequest on success.
type mergePullRequestResponse struct {
	// Merge a pull request.
	MergePullRequest mergePullRequestMergePullRequestMergePullRequestPayload `json:"mergePullRequest"`
}

// GetMergePullRequest returns mergePullRequestResponse.MergePullRequest, and is useful for accessing the field via an interface.
func (v *mergePullRequestResponse) GetMergePullRequest() mergePullRequestMergePullRequestMergePullRequestPayload {
	return v.MergePullRequest
}

// The query or mutation executed by createIssue.
const createIssue_Operation = `
mutation createIssue ($Body: String!, $Title: String!, $RepositoryId: ID!) {
	createIssue(input: {body:$Body,title:$Title,repositoryId:$RepositoryId}) {
		issue {
			id
		}
	}
}
`

func createIssue(
	ctx_ context.Context,
	client_ graphql.Client,
	Body string,
	Title string,
	RepositoryId string,
) (*createIssueResponse, error) {
	req_ := &graphql.Request{
		OpName: "createIssue",
		Query:  createIssue_Operation,
		Variables: &__createIssueInput{
			Body:         Body,
			Title:        Title,
			RepositoryId: RepositoryId,
		},
	}
	var err_ error

	var data_ createIssueResponse
	resp_ := &graphql.Response{Data: &data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return &data_, err_
}

// The query or mutation executed by createPullRequest.
const createPullRequest_Operation = `
mutation createPullRequest ($BaseRefName: String!, $Body: String!, $HeadRefName: String!, $RepositoryId: ID!, $Title: String!) {
	createPullRequest(input: {baseRefName:$BaseRefName,body:$Body,headRefName:$HeadRefName,repositoryId:$RepositoryId,title:$Title}) {
		pullRequest {
			id
			number
		}
	}
}
`

func createPullRequest(
	ctx_ context.Context,
	client_ graphql.Client,
	BaseRefName string,
	Body string,
	HeadRefName string,
	RepositoryId string,
	Title string,
) (*createPullRequestResponse, error) {
	req_ := &graphql.Request{
		OpName: "createPullRequest",
		Query:  createPullRequest_Operation,
		Variables: &__createPullRequestInput{
			BaseRefName:  BaseRefName,
			Body:         Body,
			HeadRefName:  HeadRefName,
			RepositoryId: RepositoryId,
			Title:        Title,
		},
	}
	var err_ error

	var data_ createPullRequestResponse
	resp_ := &graphql.Response{Data: &data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return &data_, err_
}

// The query or mutation executed by getCommitGitHubActionsRuns.
const getCommitGitHubActionsRuns_Operation = `
query getCommitGitHubActionsRuns ($owner: String!, $repo: String!, $commitSha: GitObjectID!) {
	repository(owner: $owner, name: $repo) {
		object(oid: $commitSha) {
			__typename
			... on Commit {
				statusCheckRollup {
					contexts(last: 10) {
						nodes {
							__typename
							... on CheckRun {
								name
								conclusion
								status
								detailsUrl
							}
						}
					}
				}
			}
		}
	}
}
`

func getCommitGitHubActionsRuns(
	ctx_ context.Context,
	client_ graphql.Client,
	owner string,
	repo string,
	commitSha string,
) (*getCommitGitHubActionsRunsResponse, error) {
	req_ := &graphql.Request{
		OpName: "getCommitGitHubActionsRuns",
		Query:  getCommitGitHubActionsRuns_Operation,
		Variables: &__getCommitGitHubActionsRunsInput{
			Owner:     owner,
			Repo:      repo,
			CommitSha: commitSha,
		},
	}
	var err_ error

	var data_ getCommitGitHubActionsRunsResponse
	resp_ := &graphql.Response{Data: &data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return &data_, err_
}

// The query or mutation executed by getLatestDeployments.
const getLatestDeployments_Operation = `
query getLatestDeployments ($owner: String!, $repo: String!) {
	repository(owner: $owner, name: $repo) {
		deployments(last: 10) {
			nodes {
				createdAt
				commit {
					message
				}
				description
				state
				statuses(first: 10) {
					nodes {
						updatedAt
						state
						environment
					}
				}
			}
		}
	}
}
`

func getLatestDeployments(
	ctx_ context.Context,
	client_ graphql.Client,
	owner string,
	repo string,
) (*getLatestDeploymentsResponse, error) {
	req_ := &graphql.Request{
		OpName: "getLatestDeployments",
		Query:  getLatestDeployments_Operation,
		Variables: &__getLatestDeploymentsInput{
			Owner: owner,
			Repo:  repo,
		},
	}
	var err_ error

	var data_ getLatestDeploymentsResponse
	resp_ := &graphql.Response{Data: &data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return &data_, err_
}

// The query or mutation executed by getPullRequestStatusCheckRollup.
const getPullRequestStatusCheckRollup_Operation = `
query getPullRequestStatusCheckRollup ($owner: String!, $repo: String!, $prNumber: Int!) {
	repository(owner: $owner, name: $repo) {
		pullRequest(number: $prNumber) {
			statusCheckRollup {
				state
			}
		}
	}
}
`

func getPullRequestStatusCheckRollup(
	ctx_ context.Context,
	client_ graphql.Client,
	owner string,
	repo string,
	prNumber int,
) (*getPullRequestStatusCheckRollupResponse, error) {
	req_ := &graphql.Request{
		OpName: "getPullRequestStatusCheckRollup",
		Query:  getPullRequestStatusCheckRollup_Operation,
		Variables: &__getPullRequestStatusCheckRollupInput{
			Owner:    owner,
			Repo:     repo,
			PrNumber: prNumber,
		},
	}
	var err_ error

	var data_ getPullRequestStatusCheckRollupResponse
	resp_ := &graphql.Response{Data: &data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return &data_, err_
}

// The query or mutation executed by getRepoId.
const getRepoId_Operation = `
query getRepoId ($Owner: String!, $Name: String!) {
	repository(owner: $Owner, name: $Name) {
		id
	}
}
`

func getRepoId(
	ctx_ context.Context,
	client_ graphql.Client,
	Owner string,
	Name string,
) (*getRepoIdResponse, error) {
	req_ := &graphql.Request{
		OpName: "getRepoId",
		Query:  getRepoId_Operation,
		Variables: &__getRepoIdInput{
			Owner: Owner,
			Name:  Name,
		},
	}
	var err_ error

	var data_ getRepoIdResponse
	resp_ := &graphql.Response{Data: &data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return &data_, err_
}

// The query or mutation executed by getUser.
const getUser_Operation = `
query getUser ($Login: String!) {
	user(login: $Login) {
		theirName: name
		createdAt
	}
}
`

// getUser gets the given user's name from their username.
func getUser(
	ctx_ context.Context,
	client_ graphql.Client,
	Login string,
) (*getUserResponse, error) {
	req_ := &graphql.Request{
		OpName: "getUser",
		Query:  getUser_Operation,
		Variables: &__getUserInput{
			Login: Login,
		},
	}
	var err_ error

	var data_ getUserResponse
	resp_ := &graphql.Response{Data: &data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return &data_, err_
}

// The query or mutation executed by getViewer.
const getViewer_Operation = `
query getViewer {
	viewer {
		MyName: name
		createdAt
	}
}
`

func getViewer(
	ctx_ context.Context,
	client_ graphql.Client,
) (*getViewerResponse, error) {
	req_ := &graphql.Request{
		OpName: "getViewer",
		Query:  getViewer_Operation,
	}
	var err_ error

	var data_ getViewerResponse
	resp_ := &graphql.Response{Data: &data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return &data_, err_
}

// The query or mutation executed by mergePullRequest.
const mergePullRequest_Operation = `
mutation mergePullRequest ($pullRequestId: ID!) {
	mergePullRequest(input: {pullRequestId:$pullRequestId,mergeMethod:SQUASH}) {
		pullRequest {
			merged
			mergedAt
			mergeCommit {
				oid
			}
		}
	}
}
`

func mergePullRequest(
	ctx_ context.Context,
	client_ graphql.Client,
	pullRequestId string,
) (*mergePullRequestResponse, error) {
	req_ := &graphql.Request{
		OpName: "mergePullRequest",
		Query:  mergePullRequest_Operation,
		Variables: &__mergePullRequestInput{
			PullRequestId: pullRequestId,
		},
	}
	var err_ error

	var data_ mergePullRequestResponse
	resp_ := &graphql.Response{Data: &data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return &data_, err_
}
